### ISSUE TITLE
DSI exception after initializing network

### ISSUE THREAD

**Issue by emilydaemon** [OpenShopChannel/libreshop-client#1]
bug noticed by `@windowslover3545` (discord username) in the WiiLink server

![image](https://github.com/user-attachments/assets/f974b0a3-2675-4522-88b8-021492e71e26)

gdb provides no line information for any of the code dump addresses, unfortunately

**Comment by Team240Games-BarOS** [comment]
basically needed a connection initalize, didnt even want to connect to libreshop so it decided to not work and just crash my wii, image was taken through my capture card (EasyCap)
details of my device




RVL-101 (non Boot2 compatible, Family Edition. no GameCube support)
real hardware used
SD card in use
wifi connected

**Comment by Naim2000** [comment]
@emilydaemon 

> gdb provides no line information for any of the code dump addresses, unfortunately

Make sure `-g` is in CFLAGS
And, make sure that you send them your build of the app, you don't want addresses not matching up

**Comment by emilydaemon** [comment]
No longer reproducible
